# Generated by Django 4.2.30 on 2026-06-09 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('postcode', models.CharField(max_length=8)),
                ('grid_zone_id', models.CharField(blank=True, max_length=15, null=True)),
                ('relative_compactness', models.FloatField()),
                ('surface_area', models.FloatField()),
                ('wall_area', models.FloatField()),
                ('roof_area', models.FloatField()),
                ('overall_height', models.FloatField()),
                ('orientation', models.IntegerField()),
                ('glazing_area', models.FloatField()),
                ('glazing_area_distribution', models.IntegerField()),
                ('calculated_base_load_kw', models.FloatField(blank=True, null=True)),
                ('thermal_inertia_coefficient', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlexibleAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('electrical_capacity_kw', models.FloatField()),
                ('criticality_classification', models.CharField(choices=[('CRITICAL', 'Critical'), ('FLEXIBLE', 'Flexible'), ('SHEDDABLE', 'Sheddable')], max_length=20)),
                ('is_modulated_active', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flexible_assets', to='api.buildingprofile')),
            ],
        ),
    ]
