# Generated by Django 4.2.30 on 2026-06-19 17:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_json', models.JSONField()),
                ('recommendation_text', models.TextField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.buildingprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CarbonPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_intensity_threshold', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('daily_carbon_budget_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('automation_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_preference', to='api.buildingprofile')),
            ],
        ),
    ]
