# Generated by Django 4.2.30 on 2026-06-20 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_operationalschedule_carbonpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingprofile',
            name='glazing_area',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='buildingprofile',
            name='overall_height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='buildingprofile',
            name='relative_compactness',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='buildingprofile',
            name='roof_area',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='buildingprofile',
            name='surface_area',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='buildingprofile',
            name='wall_area',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
