# Generated by Django 4.2.30 on 2026-06-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_buildingprofile_glazing_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingprofile',
            name='predicted_cooling_load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildingprofile',
            name='predicted_heating_load',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
