# Generated by Django 4.2.30 on 2026-06-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_buildingprofile_predicted_cooling_load_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingprofile',
            name='predicted_cooling_load',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='buildingprofile',
            name='predicted_heating_load',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
