# Generated by Django 4.2.30 on 2026-06-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_buildingprofile_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CARBON_SPIKE', 'Carbon Intensity Spike'), ('SCHEDULE_READY', 'Schedule Ready')], max_length=32)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('forecast_window_start', models.DateTimeField(blank=True, null=True)),
                ('forecast_window_end', models.DateTimeField(blank=True, null=True)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('forecast_peak_value', models.FloatField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('recipient', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivery_reason', models.TextField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='api.buildingprofile')),
            ],
        ),
    ]
