# Generated by Django 4.2.30 on 2026-06-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_notificationevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingprofile',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
