# Generated by Django 4.2.30 on 2026-06-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_buildingprofile_user_email'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='buildingprofile',
            constraint=models.UniqueConstraint(fields=('owner', 'postcode'), name='unique_owner_postcode'),
        ),
    ]
