# Generated by Django 4.2.30 on 2026-06-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_buildingprofile_unique_owner_postcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarbonForecast",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("region_id", models.CharField(db_index=True, max_length=16)),
                ("forecast_time", models.DateTimeField(db_index=True)),
                ("fetched_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("source", models.CharField(default="national_grid_eso", max_length=64)),
                ("intensity_forecast", models.FloatField()),
                ("generation_mix", models.JSONField(blank=True, default=list)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["region_id", "forecast_time"],
            },
        ),
        migrations.AddConstraint(
            model_name="carbonforecast",
            constraint=models.UniqueConstraint(fields=("region_id", "forecast_time"), name="unique_region_forecast_timestamp"),
        ),
        migrations.AddIndex(
            model_name="carbonforecast",
            index=models.Index(fields=["region_id", "forecast_time"], name="idx_region_forecast_time"),
        ),
    ]
