# Generated by Django 4.2.30 on 2026-06-29 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_carbonforecast"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="buildingprofile",
            name="unique_owner_postcode",
        ),
    ]
