# Generated by Django 4.2.30 on 2026-06-29 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_unique_owner_postcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('DELAYED', 'Delayed'), ('REDUCED', 'Reduced Capacity'), ('SHUTDOWN', 'Temporarily Shutdown'), ('RESTORED', 'Restored to Normal')], max_length=20)),
                ('trigger_type', models.CharField(choices=[('AUTOMATIC', 'Automatic (Carbon Threshold)'), ('MANUAL', 'Manual User Override'), ('SCHEDULED', 'Pre-scheduled')], default='AUTOMATIC', max_length=20)),
                ('carbon_intensity_at_time', models.FloatField(help_text='gCO2/kWh')),
                ('carbon_threshold', models.FloatField(help_text='Threshold that triggered action')),
                ('previous_state', models.BooleanField(help_text='Previous is_modulated_active state')),
                ('new_state', models.BooleanField(help_text='New is_modulated_active state')),
                ('reason', models.TextField(help_text='Human-readable reason for modulation')),
                ('estimated_carbon_saved_kg', models.FloatField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='How long the modulation lasted (filled when restored)', null=True)),
                ('initiated_by', models.CharField(blank=True, help_text="User email if manual, 'system' if automatic", max_length=100, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulation_events', to='api.flexibleasset')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulation_events', to='api.buildingprofile')),
            ],
            options={
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['building', '-triggered_at'], name='idx_building_modulation'), models.Index(fields=['asset', '-triggered_at'], name='idx_asset_modulation')],
            },
        ),
    ]
