# api/serializers.py
from rest_framework import serializers
from .models import BuildingProfile, FlexibleAsset

class BuildingProfileSerializer(serializers.ModelSerializer):
    class Meta:
        model = BuildingProfile
        fields = '__all__'
        # These are generated by PyTorch and the National Grid API internally, so they are read-only
        read_only_fields = ['grid_zone_id', 'calculated_base_load_kw', 'thermal_inertia_coefficient']

    def validate_postcode(self, value):
        """
        Cleanses and validates UK postcodes to ensure reliable grid zone mapping.
        """
        clean_pc = value.replace(" ", "").upper()
        if len(clean_pc) < 5 or len(clean_pc) > 8:
            raise serializers.ValidationError("Postcode format must adhere to standard UK grid constraints.")
        return clean_pc


class FlexibleAssetSerializer(serializers.ModelSerializer):
    class Meta:
        model = FlexibleAsset
        fields = '__all__'