# api/serializers.py
from rest_framework import serializers
from .models import BuildingProfile, FlexibleAsset
from .models import OperationalSchedule
from rest_framework import serializers
from .models import CarbonPreference

class CarbonPreferenceSerializer(serializers.ModelSerializer):

    class Meta:
        model = CarbonPreference
        fields = [
            "id",
            "building",
            "carbon_intensity_threshold",
            "daily_carbon_budget_kg",
            "automation_enabled"
        ]

    def validate_carbon_intensity_threshold(self, value):
        if value < 0:
            raise serializers.ValidationError(
                "Carbon intensity threshold cannot be negative."
            )
        return value

    def validate_daily_carbon_budget_kg(self, value):
        if value < 0:
            raise serializers.ValidationError(
                "Daily carbon budget cannot be negative."
            )
        return value

    # Optional: object-level validation (future-proof)
    def validate(self, data):
        if (
            data.get("carbon_intensity_threshold", 0) < 0 or
            data.get("daily_carbon_budget_kg", 0) < 0
        ):
            raise serializers.ValidationError("Invalid carbon constraints.")
        return data
    
class BuildingProfileSerializer(serializers.ModelSerializer):
    class Meta:
        model = BuildingProfile
        fields = '__all__'
        # These are generated by PyTorch and the National Grid API internally, so they are read-only
        read_only_fields = ['grid_zone_id', 'calculated_base_load_kw', 'thermal_inertia_coefficient']

    def validate_postcode(self, value):
        """
        Cleanses and validates UK postcodes to ensure reliable grid zone mapping.
        """
        clean_pc = value.replace(" ", "").upper()
        if len(clean_pc) < 5 or len(clean_pc) > 8:
            raise serializers.ValidationError("Postcode format must adhere to standard UK grid constraints.")
        return clean_pc


class FlexibleAssetSerializer(serializers.ModelSerializer):
    class Meta:
        model = FlexibleAsset
        fields = '__all__'


class OperationalScheduleSerializer(serializers.ModelSerializer):
    class Meta:
        model = OperationalSchedule
        fields = "__all__"