from typing import List, Dict, Any
from django.utils.dateparse import parse_datetime
from django.utils import timezone
from .email_dispatcher import send_sustainability_report
from api.models import NotificationEvent, CarbonPreference

def _compose_message(building, window_start, window_end, peak_value, threshold):
    # Simple template with operational recommendations
    return (
        f"NetZero Alert for {building.postcode}\n\n"
        f"Forecast window: {window_start.isoformat()} -> {window_end.isoformat()}\n"
        f"Expected peak carbon intensity: {peak_value:.1f} gCO2/kWh (threshold: {threshold:.1f})\n\n"
        "Recommended actions:\n"
        "- Shift non-critical electrical loads to outside the flagged window.\n"
        "- Pre-cool or pre-heat within the preceding low-carbon periods.\n"
        "- Delay discretionary equipment use where possible.\n\n"
        "This is an automated notification generated by NetZero."
    )


def analyze_forecast_and_notify(building, forecast: List[Dict[str, Any]], send_email: bool = True):
    """
    Analyze a list of forecast points and create NotificationEvent records for
    windows where carbon intensity exceeds the user's threshold.

    Forecast items must be dicts containing 'timestamp' (ISO str) and 'carbon_intensity' (float).
    Returns list of created NotificationEvent objects.
    """
    # Resolve threshold from CarbonPreference if present
    try:
        pref = building.carbon_preference
        threshold = float(pref.carbon_intensity_threshold)
    except Exception:
        threshold = 200.0  # conservative default (gCO2/kWh)

    # Convert forecast timestamps and find contiguous windows above threshold
    points = []
    for p in forecast or []:
        ts = p.get("timestamp")
        ci = p.get("carbon_intensity")
        if ts is None or ci is None:
            continue
        dt = parse_datetime(ts)
        if dt is None:
            continue
        if timezone.is_naive(dt):
            dt = timezone.make_aware(dt, timezone.get_current_timezone())
        points.append((dt, float(ci)))

    points.sort(key=lambda x: x[0])

    events = []
    window_start = None
    window_end = None
    peak_value = None

    for dt, ci in points:
        if ci > threshold:
            if window_start is None:
                window_start = dt
                peak_value = ci
                window_end = dt
            else:
                window_end = dt
                if ci > peak_value:
                    peak_value = ci
        else:
            if window_start is not None:
                # finalize window
                message = _compose_message(building, window_start, window_end, peak_value, threshold)
                ne = NotificationEvent.objects.create(
                    building=building,
                    event_type="CARBON_SPIKE",
                    forecast_window_start=window_start,
                    forecast_window_end=window_end,
                    threshold_value=threshold,
                    forecast_peak_value=peak_value,
                    message=message,
                    recipient=getattr(building, "user_email", None)
                )
                # attempt send
                if send_email and ne.recipient:
                    success, reason = send_sustainability_report(ne.recipient, message)
                    ne.delivered = bool(success)
                    ne.delivery_reason = reason
                    ne.save()
                events.append(ne)
                window_start = None
                window_end = None
                peak_value = None

    # handle trailing open window
    if window_start is not None:
        message = _compose_message(building, window_start, window_end, peak_value, threshold)
        ne = NotificationEvent.objects.create(
            building=building,
            event_type="CARBON_SPIKE",
            forecast_window_start=window_start,
            forecast_window_end=window_end,
            threshold_value=threshold,
            forecast_peak_value=peak_value,
            message=message,
            recipient=getattr(building, "user_email", None)
        )
        if send_email and ne.recipient:
            success, reason = send_sustainability_report(ne.recipient, message)
            ne.delivered = bool(success)
            ne.delivery_reason = reason
            ne.save()
        events.append(ne)

    return events
